print()
print("Applying Inbuilt Functions On SET")
print()
example_set={5,(5,10,15),75,57,88}
print("ADD")
example_set.add(25)
print()
print(example_set)
print("REMOVE")
example_set.remove(75)
print("example_set.remove(99)\n it throws an key error because it doesn,t have the element on it")
print()
print(example_set)
print("DISCARD")
example_set.discard(99)
print("example_set.discard(99)\nit doesn,t throws any error.\nprints the same set")
print()
example_set.pop()
print("POP")
print(example_set)
print()
print("CLEAR")
print("delets whole set")
example_set.clear()
print(example_set)
print()
example_set1={5,(5,10,15),75,57,88}
example_set2={5,(5,9,15),75,57,99}
print("UNION")
print(example_set1.union(example_set2))
print()
print("INTERSECTION")
print(example_set1.intersection(example_set2))
print(example_set2.intersection(example_set1))
print()
print("DIFFERENCE")
print(example_set1.difference(example_set2))
print(example_set2.difference(example_set1))
print()
print("Checking the set ISSUBSET of another set")
print(example_set1.issubset(example_set2))
print(example_set2.issubset(example_set1))
print()
print("Checking the set ISSUPERSET of another set")
print(example_set1.issuperset(example_set2))
print(example_set2.issuperset(example_set1))
print()
print("ISDISJOINT")
print(example_set1.isdisjoint(example_set2))
print(example_set2.isdisjoint(example_set1))

